myservers:
  hosts:
    server1:
      ansible_host: 192.168.1.152
      ansible_port: 22
      ansible_ssh_user: ansible 
      ansible_ssh_private_key_file: ansible.key
      http_host: html
      http_conf: mydomain.local.conf
  vars:
    http_port: "80"  
